# Header
menu:
  Home: /
  Archives: /archives

# SubNav
subnav:
  github: "https://github.com/justcoolls"
#  weibo: "#"
#  zhihu: "#"
#  qq: "#"
#  weixin: "#"
  jianshu: "http://www.jianshu.com/u/1dc0382931a0"
#  renren: "#"
#  douban: "#"
#  bilibili: "#"
#  acfun: "#"
#  mail: "#"
#  facebook: "#"
#  google: "#"
#  twitter: "#"
#  linkedin: "#"
#  rss: "#"

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

#你的头像url
avatar: /img/avatar.jpg

# Miscellaneous
google_analytics:
favicon: /img/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
